version: '2'
services:
  fpm:
    build:
      context: .
    container_name: fpm
    image: php-fpm
    volumes:
      - /var/www/html/dev3:/var/www/html/dev3
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /var/www/html/:/var/www/html
    ports:
      - 80:80
  mariadb:
    container_name: mariadb
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql:/var/lib/mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: password
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /var/lib/mongo:/data/db
  memcached:
    container_name: memcached
    image: memcached
    ports:
      - "11211:11211"
